### ISSUE TITLE
How can I convert "shiny for python" to ".exe" executable file.

### ISSUE THREAD

**Issue by HotWesley** [posit-dev/py-shiny#1054]
Because of the project, I need to convert Shiny for Python into an exe executable file.

I tried several tests, but I failed. Is this possible? I'm asking you directly because I don't have much data on the Internet.

I'd appreciate it if you could answer me.

Have a nice day :)

**Comment by wch** [comment]
Interesting idea. I would disagree with the assertion, however:

> `sys.stderr.write(f"Error: {module_path} not found\n")` is a bug in Shiny. It's assuming that a console is available [which isn't true for windowed applications](https://pyinstaller.org/en/latest/common-issues-and-pitfalls.html#sys-stdin-sys-stdout-and-sys-stderr-in-noconsole-windowed-applications-windows-only).

because Shiny wasn't intended for that use case.

That said, it might be worth it to try replacing `sys.stderr.write()` with `print(..., file=sys.stderr)` to see if it works with pyinstaller.

**Comment by HotWesley** [comment]
Thank you for your comment!

how about this.
I modify main.py code as below and run .exe file

```
from shiny import App, render, ui

app_ui = ui.page_fluid(
    ui.input_slider("n", "N", 0, 100, 20),
    ui.output_text_verbatim("txt"),
)


def server(input, output, session):
    @output
    @render.text
    def txt():
        return f"n*2 is {input.n() * 2}"


app = App(app_ui, server)

app.run()
```

Then this error has occurred.

```
Traceback (most recent call last):
  File "logging\config.py", line 544, in configure
  File "logging\config.py", line 656, in configure_formatter
  File "logging\config.py", line 475, in configure_custom
  File "uvicorn\logging.py", line 44, in __init__
AttributeError: 'NoneType' object has no attribute 'isatty'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 18, in <module>
  File "shiny\_app.py", line 233, in run
    run_app(self, **kwargs)  # pyright: ignore[reportGeneralTypeIssues]
  File "shiny\_main.py", line 338, in run_app
    uvicorn.run(  # pyright: ignore[reportUnknownMemberType]
  File "uvicorn\main.py", line 522, in run
  File "uvicorn\config.py", line 276, in __init__
  File "uvicorn\config.py", line 384, in configure_logging
  File "logging\config.py", line 811, in dictConfig
  File "logging\config.py", line 547, in configure
ValueError: Unable to configure formatter 'default
```
