### ISSUE TITLE
Wildcard import from express errors out

### ISSUE THREAD

**Issue by cpsievert** [posit-dev/py-shiny#1065]
```python
from shiny.express import *

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cpsievert/github/py-shiny/shiny/express/__init__.py", line 46, in __getattr__
    return _get_current_session().input  # pyright: ignore
AttributeError: 'NoneType' object has no attribute 'input'
```

**Comment by wch** [comment]
I'm not able to reproduce this. Here's a screenshot:

<img width="739" alt="image" src="https://github.com/posit-dev/py-shiny/assets/86978/fc622c6e-fdf5-424a-a7d7-99cfdf0c7fb0">


When it does the UI rendering pass, `get_current_session()` should return a `MockSession` object. For example, with this app:

```py
from shiny.express import *

print(session)
print(input)
"Hello"
```

it prints the following to the console:

```
<shiny.express._mock_session.MockSession object at 0x102010f90>
<shiny.session._session.Inputs object at 0x1020110d0>
INFO:     Started server process [95498]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:55016 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:55019 - "GET /?vscodeBrowserReqId=1706155679039 HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 55022) - "WebSocket /websocket/" [accepted]
INFO:     connection open
<shiny.session._session.Session object at 0x102174550>
<shiny.session._session.Inputs object at 0x10069f8d0>
```

**Comment by wch** [comment]
Update: I _am_ able to reproduce this by running it at the console.

```
>>> from shiny.express import *

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/winston/Projects/py-shiny/shiny/express/__init__.py", line 46, in __getattr__
    return _get_current_session().input  # pyright: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'input'

>>> from shiny.express import input
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'input' from 'shiny.express' (/Users/winston/Projects/py-shiny/shiny/express/__init__.py)
```
