### ISSUE TITLE
Cannot run `shiny run` with `--reload`

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/py-shiny#1188]
After #1183, running `shiny run --reload` results in an error when trying to `cast(ASGI3Application, app)`

https://github.com/posit-dev/py-shiny/blob/0b170d3e3a7e57182cae34b3ec9b03320da3f962/shiny/_autoreload.py#L107

```
INFO:     Uvicorn running on http://127.0.0.1:52287 (Press CTRL+C to quit)
INFO:     Started reloader process [75586] using WatchFiles
INFO:     Started server process [75591]
INFO:     Waiting for application startup.
ERROR:    Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "/Users/garrick/work/posit-dev/py-shiny/venv/lib/python3.11/site-packages/uvicorn/lifespan/on.py", line 86, in main
    await app(scope, self.receive, self.send)
  File "/Users/garrick/work/posit-dev/py-shiny/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/garrick/work/posit-dev/py-shiny/shiny/_app.py", line 275, in __call__
    await self.starlette_app(scope, receive, send)
  File "/Users/garrick/work/posit-dev/py-shiny/venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    self.middleware_stack = self.build_middleware_stack()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/garrick/work/posit-dev/py-shiny/venv/lib/python3.11/site-packages/starlette/applications.py", line 109, in build_middleware_stack
    app = cls(app=app, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/garrick/work/posit-dev/py-shiny/shiny/_autoreload.py", line 107, in __init__
    self.app = cast(ASGI3Application, app)
                    ^^^^^^^^^^^^^^^^
NameError: name 'ASGI3Application' is not defined
ERROR:    Application startup failed. Exiting.
```

cc @wch

**Comment by wch** [comment]
This was due to changes I made in #1183: it loaded some types only when `typing.TYPE_CHECKING` is true, so that those types were only loaded during the static analysis phase, but later in the code it used `cast()` with some of those types, and that happens at run time, when types aren't loaded. I have a fix where the casting only occurs when `TYPE_CHECKING` is true.

I wish Python's type system was more consistent in how it worked, and was completely ignored at run time, instead of being mostly being ignored but with a few exceptions like `cast()`.
