### ISSUE TITLE
Remove `yarn.lock` file?

### ISSUE THREAD

**Issue by cpsievert** [posit-dev/py-shiny#1288]
Currently we have both a `yarn.lock` and a `package-lock.json`. When I do `yarn install && yarn build`, I see the following error:

```shell
yarn run v1.22.19
$ npm run lint && npm run bundle

> lint
> tsc -noEmit && eslint .


Oops! Something went wrong! :(

ESLint: 7.21.0

Error: Failed to load plugin 'react' declared in '.eslintrc.js': Cannot find module 'eslint/package.json'
Require stack:
- /Users/cpsievert/github/py-shiny/js/node_modules/eslint-plugin-react/lib/util/message.js
- /Users/cpsievert/github/py-shiny/js/node_modules/eslint-plugin-react/lib/util/report.js
- /Users/cpsievert/github/py-shiny/js/node_modules/eslint-plugin-react/lib/rules/boolean-prop-naming.js
- /Users/cpsievert/github/py-shiny/js/node_modules/eslint-plugin-react/lib/rules/index.js
- /Users/cpsievert/github/py-shiny/js/node_modules/eslint-plugin-react/configs/all.js
- /Users/cpsievert/github/py-shiny/js/node_modules/eslint-plugin-react/index.js
- /usr/local/lib/node_modules/eslint/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /usr/local/lib/node_modules/eslint/node_modules/@eslint/eslintrc/lib/index.js
- /usr/local/lib/node_modules/eslint/lib/cli-engine/cli-engine.js
- /usr/local/lib/node_modules/eslint/lib/eslint/eslint.js
- /usr/local/lib/node_modules/eslint/lib/eslint/index.js
- /usr/local/lib/node_modules/eslint/lib/cli.js
- /usr/local/lib/node_modules/eslint/bin/eslint.js
Referenced from: /Users/cpsievert/github/py-shiny/js/.eslintrc.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (/usr/local/lib/node_modules/eslint/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/cpsievert/github/py-shiny/js/node_modules/eslint-plugin-react/lib/util/message.js:4:19)
    at Module._compile (/usr/local/lib/node_modules/eslint/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I suppose it would be nice to fix this error, but based on our CI, it seems an intentional choice to use `npm` instead, which works fine for me. So maybe we just remove the `yarn.lock` for now to avoid confusion?

**Comment by cpsievert** [comment]
Oh geez, I just realized there is no `yarn.lock` 🤦
