### ISSUE TITLE
Express: Cannot create a navbar page with an `id` and a sidebar

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/py-shiny#1308]
It's common to want to add a global sidebar to a navbar page _and_ to have some content in that sidebar be displayed conditionally. With Shiny Core, you can create an app with this layout using the following code:

```python
from shiny import App, ui

ui = ui.page_navbar(
    ui.nav_panel("A", "Page A content"),
    ui.nav_panel("B", "Page B content"),  # <2>
    title="App with navbar",
    fillable=True,
    id="page",  # <1>
    sidebar=ui.sidebar(
        ui.input_select("data", "Data", ("A", "B", "C")),
        ui.panel_conditional(
            "input.page === 'B'",  # <3>
            ui.input_select("subset", "Subset for B", ("e", "f", "g")),
        ),
    ),
)


def server(input):
    pass


app = App(ui, server)
```

<p align="right"><a href="https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxMArhwA6EOdKYBeKRyxQA5nAD60AG4AjKHQAUcphdUZ921FAhwANmbAiZ+Ju4AKmuKKYk5JRk7gCUeOaW0tZQerb2Ti4AQu4S3r5MSQGkFORhEkwAxEwAPABMAHyRFmQcZI5wSu5iqEwA7nVsTPpGdKnVTDQcjo5QBg1KACp0knAREJa8ACZNYHZaqRbFJQCMVQuWLBxLcL1K0UcnvWYHixbRXKiSZNosTnCEZC5LUGRQm+4ACK-f4eFxuDzuFKQsAAYTC4QGi2idgcjm0gSWdQ4pCgziRdws7kez3UWmUShUAHIklTNkVSgBmfaEwkPCBPF5vBqfFwsSQGN4hGEAZQFQsGgkymxccABtHlGgR81ZTERtzV81Cch1EBONFYcDoeiNJhJZFCiAGdhYLF1cjQrRULRM0gkb2NRtCYAAvgBdIA">shinylive.io example</a></p>

There are three components:

1. The `ui.page_navbar()` needs the `id` argument.
2. When `id` is provided, the current page title is reported at that `input.{id}`.
3. `ui.panel_conditional()` can use the value of the input, e.g. `input.page === 'B'`, to display content only when `nav_panel("B", ...)` is displayed.

In Shiny Express, this pattern is not possible because users cannot set `id` via `ui.page_opts()`. In theory, they would need to provide a custom function to `ui.page_opts(page_fn=)` that passes `id` to `shiny.ui.page_navbar()`.

```python
from shiny.express import input, ui
from functools import partial
from shiny.ui import page_navbar

def page_navbar_id(*args, **kwargs):
    return page_navbar(*args, **kwargs, id="page")

## Doesn't work
ui.page_opts(title="App with navbar", fillable=True, page_fn=page_navbar_id)
## Does work, but can't set the page `id`
# ui.page_opts(title="App with navbar", fillable=True)

with ui.sidebar(title="Settings"):
    ui.input_select("data", "Data", ("A", "B", "C"))

    with ui.panel_conditional("input.page === 'Settings B'"):
        ui.input_select("subset", "Subset for B", ("e", "f", "g"))

with ui.nav_panel("A"):
    "Page A content"

with ui.nav_panel("B"):
    "Page B content"
```

<p align="right"><a href="https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbDOAD1R04LFkw4xUxOmTERUAVzJ4m8jgB0I9RkxryIhMsWIAbUeMnSmqKNI5RjGrc3ZceqsRKkzrAczgB9aAA3ACMbDQ0AEzgaKyg-QKhQm38OSIAKACobHxZlTMyAawB3HJYASkQNJhqmITJ5Ogg4hOCwuiyy-KLSulzlNIBeNTBfOBHyiIgAYmmmABFiYQgAchliqUKNVSx4gOJUMhZ0sg4yYzhhsABBdCZis7YmNvD8HQ5jYygQi8GAFTo8jgyjG-hoEEGoJedFSkUmMzmi2E902yhCiiYhCgqxkLDgMjIbDgLWJAAM0qSNHMdqCDkcTmdfiNbqh7o9nkl2iNlDQPl8fpcAUD4RoHoSVBwMCw0nB2gzzpcRgBlfGnCC5CZVZq1HZcBRkfx4i4GdIjSJQMhQblMEbzC1Wt6mm7WkYAIRdYAAwhMRdqamKnjTsXBjP4SBBImcOKR7E69Ypdn4mIMU0wViqyGrckxXStNdVaoXdXJFIaQ3ATSMWPIQniyB6lTW6zopDnrU7xm8RjQPT4fVMAxKMMF-NYICGndd836bWAAAp7JjXTGkCjkEYD9k7Edjidu6eFkYLpOulfkSj1sBgAC+AF0gA">shinylive.io example</a></p>

This doesn't work, however, because the special handling for the top-level `with ui.sidebar()` only happens when `page_fn is None`.

https://github.com/posit-dev/py-shiny/blob/340858af9ff78b99c17f85e2350b2762fd08ac77/shiny/ui/_page.py#L543-L545

https://github.com/posit-dev/py-shiny/blob/340858af9ff78b99c17f85e2350b2762fd08ac77/shiny/ui/_page.py#L556

Attempting to run the example above using `ui.page_opts(page_fn)` gives the following error

```
Traceback (most recent call last):
  File "/Users/garrick/work/posit-dev/py-shiny/shiny/express/_run.py", line 60, in wrap_express_app
    app_ui = run_express(file).tagify()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/garrick/work/posit-dev/py-shiny/venv/lib/python3.12/site-packages/htmltools/_core.py", line 735, in tagify
    cp.children = cp.children.tagify()
                  ^^^^^^^^^^^^^^^^^^^^
  File "/Users/garrick/work/posit-dev/py-shiny/venv/lib/python3.12/site-packages/htmltools/_core.py", line 222, in tagify
    tagified_child = child.tagify()
                     ^^^^^^^^^^^^^^
  File "/Users/garrick/work/posit-dev/py-shiny/venv/lib/python3.12/site-packages/htmltools/_core.py", line 735, in tagify
    cp.children = cp.children.tagify()
                  ^^^^^^^^^^^^^^^^^^^^
  File "/Users/garrick/work/posit-dev/py-shiny/venv/lib/python3.12/site-packages/htmltools/_core.py", line 222, in tagify
    tagified_child = child.tagify()
                     ^^^^^^^^^^^^^^
  File "/Users/garrick/work/posit-dev/py-shiny/shiny/ui/_navs.py", line 396, in tagify
    nav, content = render_navset(
                   ^^^^^^^^^^^^^^
  File "/Users/garrick/work/posit-dev/py-shiny/shiny/ui/_navs.py", line 1314, in render_navset
    selected = x.get_value()
               ^^^^^^^^^^^
AttributeError: 'Sidebar' object has no attribute 'get_value'
```

**Comment by gadenbuie** [comment]
We're going to move forward with passing `kwargs` (#1314), but we also discussed that this situation would be improved by resolving #939.
