### ISSUE TITLE
installing `shiny` via conda does not install `questionary`

### ISSUE THREAD

**Issue by gernophil** [posit-dev/py-shiny#1430]
Hey,

I was just installing shiny via conda and tried to use `shiny create`. This fails however with a `ModuleNotFoundError`. It seems like shiny on conda does not install `questionary` as a dependency (at least on Apple Silicon). Would be nice, if this would be installed automatically:
```
% shiny create
Traceback (most recent call last):
  File "/Users/gernophil/miniconda3/envs/shiny/bin/shiny", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/gernophil/miniconda3/envs/shiny/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gernophil/miniconda3/envs/shiny/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/gernophil/miniconda3/envs/shiny/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gernophil/miniconda3/envs/shiny/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gernophil/miniconda3/envs/shiny/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gernophil/miniconda3/envs/shiny/lib/python3.12/site-packages/shiny/_main.py", line 561, in create
    from ._template_utils import template_query, use_git_template
  File "/Users/gernophil/miniconda3/envs/shiny/lib/python3.12/site-packages/shiny/_template_utils.py", line 14, in <module>
    import questionary
ModuleNotFoundError: No module named 'questionary'
```

**Comment by wch** [comment]
Hopefully this will fix that issue: https://github.com/conda-forge/py-shiny-feedstock/pull/39

**Comment by wch** [comment]
That PR did not fix it, but I edited the meta.yaml directly here: https://github.com/conda-forge/py-shiny-feedstock/commit/681255e67e9ae40ba3011718f04d6e7588dcd67b

**Comment by wch** [comment]
@gernophil Can you try out the latest from conda?

**Comment by gernophil** [comment]
Yes, it works now :). Thanks for the swift fix.
