### ISSUE TITLE
Empty `input_date()` crashes Shiny

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/py-shiny#1528]
Reproducible on [shinylive as of 2024-07-15](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbDOAD1R04LFkw4xUxOmSYBXDgB0IS+RhhQ6AawAmxAO4QAFEqammCsBasQzTAMR2mAJTiD+Jsx9MAROABs4CiYoPz8mYhomMjY4KP4ZLiiYpm0oIK5UWRkAI399DC8mABVktFQmPQ5QpkI6KHYCm09LFqUASiUVDgwMrIB9VIpjMEG4AEYLPHMwbzS4REmmADcQ2TgAXgsAJgAGMYA2AFodrcOtgE4LNrAAXwBdIA).

```python
from shiny.express import ui

ui.markdown(
    """
    ## Reprex
    
    Delete all of the text in the date input below.
    The app will crash.
    """
)

ui.input_date("date1", "Date:", value="2016-02-29")
```

results in this error:

```
Traceback (most recent call last):
  File "/lib/python3.12/site-packages/shiny/session/_session.py", line 644, in _run
    self._manage_inputs(message_obj["data"])
  File "/lib/python3.12/site-packages/shiny/session/_session.py", line 690, in _manage_inputs
    val = input_handlers._process_value(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/shiny/input_handler.py", line 41, in _process_value
    return handler(value, name, session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/shiny/input_handler.py", line 108, in _
    _safe_strptime_date(value[0]),
                        ~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
'NoneType' object is not subscriptable
```

**Comment by jcheng5** [comment]
This appears to have been there since day 1, I reproduced it back to 0.2.1 (summer 2022).
