### ISSUE TITLE
request: Pyodide support for `polars`; Use `polars` in shinylive examples

### ISSUE THREAD

**Issue by schloerke** [posit-dev/py-shiny#1576]
**Related:** 
* https://github.com/pola-rs/polars/issues/3672
* https://github.com/pyodide/pyodide/issues/4611

**Goal:** Display an example app using `polars` on shinylive (wasm / pyodide).

**Failing reprex:** [link](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbDOAD1R04LFkw4xUxOmTERUAVzJ4mQiABM4dZfI4AdCPp0YuCsgH0WAGw4a6ACl2RHyxwDlnTAAzKAjJ+9MAEyeAJT64RAAAqq2GCQa+ho0TGR8ZHYhiPpMOSpwZPJ0EEw0jhAAVIFioiAmihgQGUzlQQC+jvpgrXjg0PDUQgCOOkLw5CwYqWT4RKQUVMiSllB0LF0AukA)

**Error:**
```
>>> Installing polars ...
Traceback (most recent call last):
  File "<exec>", line 369, in _start_app
  File "<exec>", line 302, in _install_requirements_from_dir
  File "/lib/python3.12/site-packages/micropip/_commands/install.py", line 142, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 62, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 151, in add_requirement_inner
    await self._add_requirement_from_package_index(req)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 190, in _add_requirement_from_package_index
    wheel = find_wheel(metadata, req)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 281, in find_wheel
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for 'polars'.
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
You can use `await micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.
```

--------------------------

Shiny uses [`shinylive`](https://shiny.posit.co/py/docs/shinylive.html) to display its examples in the browser (via pyodide) without a central compute server. It would be nice to have `polars` in these examples. However, `polars` currently does not compile for pyodide [due to threading](https://github.com/pola-rs/polars/issues/3672#issuecomment-1178328642).

Talking with @georgestagg , he believes we can follow pattern of [`huggingface/tokenizers`'s flag where they turn off threads given an envvar value](https://github.com/pyodide/pyodide/issues/2816#issuecomment-1172030538) (or if we could determine if the target is wasm).

If a fix is found, this could be a possible technical blog post?

--------------------

Made issue for tracking. Will pick back up after [`posit::conf(2024)`](https://posit.co/conference/). The fix will most likely need to be in the [pola-rs/polars](https://github.com/pola-rs/polars/) repo.

cc @gadenbuie @wch

**Comment by georgestagg** [comment]
Sneak preview:

![Screenshot 2024-09-26 at 11 26 03](https://github.com/user-attachments/assets/f79226d6-c58b-47d7-af16-27f00b380488)

This currently requires patches to LLVM's `wasm-ld` & Rust's `rustc`, so that the [inventory](https://github.com/dtolnay/inventory) crate can be made to work with Wasm. With those patches, plus a bunch of stubbing out of currently problematic features (e.g. `cloud`, `aws`, _a bunch more..._), the core of polars can be built for Pyodide.

I will attempt to re-enable as many features as I can, then write things up in a document/blog post.

Later, we can start thinking about merging PRs to LLVM and `inventory`. If the required patches turn out to be no good, we could still create a Docker image with a custom compiler suite to build the polars wheel, and distribute the resulting binary with shinylive (I do this for webR system libraries and it works _mostly OK_).

**Comment by georgestagg** [comment]
Pyodide wheels are now being built for Polars and are available at https://github.com/pola-rs/polars/releases/tag/py-1.18.0.

**Comment by kv9898** [comment]
Seems like they removed polars from the latest version (0.28.0) due to build issues: https://pyodide.org/en/stable/project/changelog.html
