### ISSUE TITLE
ui.Theme has odd behavior when Shiny files are co-mingled with other system files (e.g. not in a standalone folder)

### ISSUE THREAD

**Issue by randyzwitch** [posit-dev/py-shiny#1604]
When running the [ui.Theme example](https://shiny.posit.co/py/api/core/ui.Theme.html?_gl=1*1ru846s*_ga*MTk3MTM0MDY1Ni4xNzEyNjgzNTY2*_ga_2C0WZ1JHG0*MTcyMjUyMzYxNC4yNDMuMS4xNzIyNTI5OTU5LjAuMC4w), you can get weird behavior if your `app.py` and `my_theme.py` files are not in a stand-alone directory. The following occurs when having these files at the root in macOS (`/Users/randyzwitch` for me):

```
(pyshiny_learning) randyzwitch@Randys-MacBook-Pro ~ % shiny run --reload --launch-browser app.py
INFO:     Will watch for changes in these directories: ['/Users/randyzwitch']
INFO:     Uvicorn running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
INFO:     Started reloader process [69143] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/randyzwitch/app.py", line 5, in <module>
    app_ui = ui.page_fluid(
             ^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/shiny/ui/_page.py", line 449, in page_fluid
    return page_bootstrap(
           ^^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/shiny/ui/_page.py", line 563, in page_bootstrap
    tags.body(shiny_page_theme_deps(theme), *args, **kwargs),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/shiny/ui/_html_deps_external.py", line 40, in shiny_page_theme_deps
    deps_theme = head_content(include_css(theme))
                              ^^^^^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/shiny/ui/_include_helpers.py", line 172, in include_css
    path_dest, hash = maybe_copy_files(file_path, include_files)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/shiny/ui/_include_helpers.py", line 216, in maybe_copy_files
    hash = get_hash(path, include_files)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/shiny/ui/_include_helpers.py", line 247, in get_hash
    key = "\n".join([get_file_key(x) for x in files])
                     ^^^^^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/site-packages/shiny/ui/_include_helpers.py", line 253, in get_file_key
    return str(path) + "-" + str(path.stat().st_mtime)
                                 ^^^^^^^^^^^
  File "/Users/randyzwitch/miniconda3/envs/pyshiny_learning/lib/python3.12/pathlib.py", line 840, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/randyzwitch/Library/Application Support/discord/SingletonCookie'
```

Moving the files to `/Users/randyzwitch/shinythemetest` resolves the issue, allowing the Shiny app to display as expected.

**Comment by gadenbuie** [comment]
This isn't specific to `ui.Theme()`; ultimately it's dependent on the behavior of `ui.include_css()`, which is what is ultimately called when `theme` is given a path to a CSS file.

Actually, I'd be curious to see if the problem persists if you take out the `theme` argument. It's possible that what's really causing the issue is `--reload` trying to keep track of all of the files in your home directory as part of the auto-reload file-watching process.
