### ISSUE TITLE
Template triggers runtime error

### ISSUE THREAD

**Issue by johanneswerner** [posit-dev/py-shiny#1612]
When I am running 

```
shiny create -t dashboard
```

and choose shiny express, it triggers the following error (I am using shiny v. 1.0.0). 

```
Traceback (most recent call last):
  File ".../lib/python3.12/site-packages/shiny/express/ui/_page.py", line 93, in page_opts
    cm = get_top_level_recall_context_manager()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.12/site-packages/shiny/express/_run.py", line 273, in get_top_level_recall_context_manager
    raise RuntimeError("No top-level recall context manager has been set.")
RuntimeError: No top-level recall context manager has been set.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../dashboard/app.py", line 10, in <module>
    ui.page_opts(title="Penguins dashboard", fillable=True)
  File ".../lib/python3.12/site-packages/shiny/express/ui/_page.py", line 97, in page_opts
    raise RuntimeError(
RuntimeError: express.ui.page_opts() can only be used inside of a standalone Shiny Express app.
```

Any ideas what is going wrong here? Did anyone else experience this? (I am using `poetry` for my folder structure)

**Comment by johanneswerner** [comment]
It turned out, I ran the script wrong. The correct call would have been

```
python -m shiny run
```

and it runs without any errors.
