### ISSUE TITLE
Bug crashes Shiny when adding custom css

### ISSUE THREAD

**Issue by jacksimpsoncartesian** [posit-dev/py-shiny#773]
Hi, when I try to add custom CSS to the app, no matter how I try to do it (example below, but also tried style sheets, etc, it always crashes the program.

`app_ui = ui.page_navbar(
    ui.tags.style("""body {font-family: Papyrus}"""),`

Error:

`  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/jsimpson/dev/Manifold/manifold-shiny-cefc/app.py", line 328, in <module>
    app = App(app_ui, server)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/_app.py", line 151, in __init__
    self.ui = self._render_page(
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/_app.py", line 369, in _render_page
    rendered = HTMLDocument(ui_res).render(lib_prefix=lib_prefix)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 891, in render
    html_ = self._gen_html_tag_tree(lib_prefix, include_version=include_version)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 944, in _gen_html_tag_tree
    html = html.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 684, in tagify
    cp.children = cp.children.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 207, in tagify
    tagified_child = child.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 684, in tagify
    cp.children = cp.children.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 207, in tagify
    tagified_child = child.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/ui/_navs.py", line 366, in tagify
    nav, content = render_navset(
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/ui/_navs.py", line 965, in render_navset
    selected = x.get_value()
AttributeError: 'Tag' object has no attribute 'get_value'
WARNING:  WatchFiles detected changes in 'app.py'. Reloading...
Process SpawnProcess-9:
Traceback (most recent call last):
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/jsimpson/dev/Manifold/manifold-shiny-cefc/app.py", line 328, in <module>
    app = App(app_ui, server)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/_app.py", line 151, in __init__
    self.ui = self._render_page(
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/_app.py", line 369, in _render_page
    rendered = HTMLDocument(ui_res).render(lib_prefix=lib_prefix)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 891, in render
    html_ = self._gen_html_tag_tree(lib_prefix, include_version=include_version)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 944, in _gen_html_tag_tree
    html = html.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 684, in tagify
    cp.children = cp.children.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 207, in tagify
    tagified_child = child.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 684, in tagify
    cp.children = cp.children.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 207, in tagify
    tagified_child = child.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 684, in tagify
    cp.children = cp.children.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 207, in tagify
    tagified_child = child.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/ui/_navs.py", line 84, in tagify
    raise NotImplementedError(
NotImplementedError: nav() items must appear within navset_*() container.
WARNING:  WatchFiles detected changes in 'app.py'. Reloading...
Process SpawnProcess-10:
Traceback (most recent call last):
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/jsimpson/dev/Manifold/manifold-shiny-cefc/app.py", line 328, in <module>
    app = App(app_ui, server)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/_app.py", line 151, in __init__
    self.ui = self._render_page(
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/_app.py", line 369, in _render_page
    rendered = HTMLDocument(ui_res).render(lib_prefix=lib_prefix)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 891, in render
    html_ = self._gen_html_tag_tree(lib_prefix, include_version=include_version)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 944, in _gen_html_tag_tree
    html = html.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 684, in tagify
    cp.children = cp.children.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 207, in tagify
    tagified_child = child.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 684, in tagify
    cp.children = cp.children.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 207, in tagify
    tagified_child = child.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/ui/_navs.py", line 366, in tagify
    nav, content = render_navset(
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/ui/_navs.py", line 965, in render_navset
    selected = x.get_value()
AttributeError: 'Tag' object has no attribute 'get_value'
WARNING:  WatchFiles detected changes in 'app.py'. Reloading...
Process SpawnProcess-11:
Traceback (most recent call last):
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/jsimpson/dev/Manifold/manifold-shiny-cefc/app.py", line 330, in <module>
    app = App(app_ui, server)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/_app.py", line 151, in __init__
    self.ui = self._render_page(
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/_app.py", line 369, in _render_page
    rendered = HTMLDocument(ui_res).render(lib_prefix=lib_prefix)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 891, in render
    html_ = self._gen_html_tag_tree(lib_prefix, include_version=include_version)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 944, in _gen_html_tag_tree
    html = html.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 684, in tagify
    cp.children = cp.children.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 207, in tagify
    tagified_child = child.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 684, in tagify
    cp.children = cp.children.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 207, in tagify
    tagified_child = child.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/ui/_navs.py", line 366, in tagify
    nav, content = render_navset(
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/ui/_navs.py", line 965, in render_navset
    selected = x.get_value()
AttributeError: 'Tag' object has no attribute 'get_value'
^CINFO:     Stopping reloader process [19309]
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$
(shiny) jsimpson@ENDGAME-WS-19:~/dev/Manifold/manifold-shiny-cefc$ shiny run --reload app.py
INFO:     Will watch for changes in these directories: ['/home/jsimpson/dev/Manifold/manifold-shiny-cefc']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [20662] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/jsimpson/dev/Manifold/manifold-shiny-cefc/app.py", line 330, in <module>
    app = App(app_ui, server)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/_app.py", line 151, in __init__
    self.ui = self._render_page(
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/_app.py", line 369, in _render_page
    rendered = HTMLDocument(ui_res).render(lib_prefix=lib_prefix)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 891, in render
    html_ = self._gen_html_tag_tree(lib_prefix, include_version=include_version)
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 944, in _gen_html_tag_tree
    html = html.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 684, in tagify
    cp.children = cp.children.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 207, in tagify
    tagified_child = child.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 684, in tagify
    cp.children = cp.children.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/htmltools/_core.py", line 207, in tagify
    tagified_child = child.tagify()
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/ui/_navs.py", line 366, in tagify
    nav, content = render_navset(
  File "/home/jsimpson/anaconda3/envs/shiny/lib/python3.9/site-packages/shiny/ui/_navs.py", line 965, in render_navset
    selected = x.get_value()
AttributeError: 'Tag' object has no attribute 'get_value'`

**Comment by jcheng5** [comment]
Thanks for the report. Unlike most page functions, `ui.page_navbar` expects its direct children to be `ui.nav`, specifically.

If you have arbitrary UI objects to add, you can do them in the `header` or `footer` arguments:

```
app_ui = ui.page_navbar(
    ui.nav_panel(...),
    ui.nav_panel(...),
    header = ui.tags.style("""body {font-family: Papyrus}"""),
)
```
