### ISSUE TITLE
Altair VConcat & HConcat charts fails with shiny==0.6.0

### ISSUE THREAD

**Issue by phobson** [posit-dev/py-shiny#835]
Hey folks -- *really* appreciate the work on project. So so useful.

I experimented with upgrading to the latest release (0.6.0) and one of my Altair charts broke. In the time that I've had today, I wasn't able to track down the exact issue, though I did make an MWE.

This happens with or without the `vega` package installed.

It's not a big deal. Shiny==0.5.1 works great for our needs locally and on shinyapp.io, but I thought I'd bring this up.

```python
"""requirements.txt
altair==5.2.0
vega-datasets==0.9.0
shiny==0.6.0
shinywidgets==0.2.4

# vega optional, downgrades pandas, fails either case
vega==4.0.0
pandas==1.5.3
"""

from shiny import App, render, ui, Inputs, Outputs, Session, reactive
from shinywidgets import render_widget, output_widget

import altair as alt
from vega_datasets import data

source = data.movies.url

def make_plot():
    return alt.Chart(source).mark_bar().encode(
        x=alt.X("IMDB_Rating:Q", bin=True),
        y='count()'
    )

app_ui = ui.page_fluid(
    ui.h1("VConcat Altair Issue"),
    ui.h4("this works"), output_widget("altair_plot_simple"),
    ui.h4("this breaks"), output_widget("altair_plot_vconcat"),
    ui.h4("this breaks"), output_widget("altair_plot_hconcat"),
)

def server(user_in: Inputs, output: Outputs, session: Session):
    @render_widget
    def altair_plot_simple():
        return make_plot()

    @render_widget
    def altair_plot_vconcat():
        return make_plot() & make_plot()

    @render_widget
    def altair_plot_hconcat():
        return make_plot() | make_plot()


if __name__ == "app":
    app = App(app_ui, server)


## launched with 
# $ python -m shiny run --port 36171 --reload "~/sources/_shiny_alt_bug/app.py"   
```

<details> <summary> Expand to see screenshot of rendered app </summary>

![image](https://github.com/posit-dev/py-shiny/assets/1163939/09cdc1ad-9eae-42e6-98be-fa376246f9af)

</details>

<details> <summary> Expand to see stack trace from console </summary>

```text
INFO:     connection open
Traceback (most recent call last):
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/shiny/session/_session.py", line 1023, in output_obs
    message[output_name] = renderer_fn()
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/shiny/render/transformer/_transformer.py", line 407, in __call__
    return run_coro_sync(self._run())
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/shiny/_utils.py", line 304, in run_coro_sync
    coro.send(None)
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/shiny/render/transformer/_transformer.py", line 322, in _run
    ret = await self._transformer(
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/shinywidgets/_shinywidgets.py", line 222, in WidgetTransformer
    widget, fill = set_layout_defaults(widget)
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/shinywidgets/_shinywidgets.py", line 349, in set_layout_defaults
    widget.chart = widget.chart.properties(width="container", height="container")  # type: ignore
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/traitlets/traitlets.py", line 718, in __set__
    self.set(obj, value)
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/traitlets/traitlets.py", line 707, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/traitlets/traitlets.py", line 1515, in _notify_trait
    self.notify_change(
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/ipywidgets/widgets/widget.py", line 701, in notify_change
    super().notify_change(change)
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/traitlets/traitlets.py", line 1527, in notify_change
    return self._notify_observers(change)
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/traitlets/traitlets.py", line 1570, in _notify_observers
    c(event)
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/altair/jupyter/jupyter_chart.py", line 210, in _on_change_chart
    self.spec = new_chart.to_dict()
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/altair/vegalite/v5/api.py", line 961, in to_dict
    vegalite_spec = super(TopLevelMixin, copy).to_dict(  # type: ignore[misc]
  File "/home/paul/mambaforge/envs/shiny-alt-bug/lib/python3.9/site-packages/altair/utils/schemapi.py", line 979, in to_dict
    raise SchemaValidationError(self, err) from None
altair.utils.schemapi.SchemaValidationError: `VConcatChart` has no parameter named 'height'

Existing parameter names are:
vconcat      center     description   params    title       
autosize     config     name          resolve   transform   
background   data       padding       spacing   usermeta    
bounds       datasets                                       

See the help for `VConcatChart` to read the full description of these parameters
```

</details>

**Comment by phobson** [comment]
...aaaaaand right as I hit send it occurred to me that I need to check the shinywidgets repo for issues as well :/

Apologies for the noise

**Comment by phobson** [comment]
ohhh the shame https://github.com/posit-dev/py-shinywidgets/issues/123
